const ROLES = {
  ADMIN: 'Admin',
  LIBRARIAN: 'Librarian',
  MEMBER: 'Member',
  HOD: 'HOD',
};

const ISSUE_STATUS = {
  ISSUED: 'Issued',
  RETURNED: 'Returned',
  OVERDUE: 'Overdue',
};

const FINE_STATUS = {
  PENDING: 'Pending',
  PAID: 'Paid',
  WAIVED: 'Waived',
};

const RESERVATION_STATUS = {
  PENDING: 'Pending',
  READY: 'Ready',
  COMPLETED: 'Completed',
  CANCELLED: 'Cancelled',
  EXPIRED: 'Expired',
};

const MEMBER_STATUS = {
  ACTIVE: 'Active',
  EXPIRED: 'Expired',
  SUSPENDED: 'Suspended',
};

const MEMBER_TYPES = {
  STUDENT: 'Student',
  FACULTY: 'Faculty',
  STAFF: 'Staff',
  STANDARD: 'Standard',
  PREMIUM: 'Premium',
};

const ACTIVITY_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  BOOK_CREATED: 'BOOK_CREATED',
  BOOK_UPDATED: 'BOOK_UPDATED',
  BOOK_DELETED: 'BOOK_DELETED',
  MEMBER_CREATED: 'MEMBER_CREATED',
  MEMBER_UPDATED: 'MEMBER_UPDATED',
  MEMBER_DELETED: 'MEMBER_DELETED',
  BOOK_ISSUED: 'BOOK_ISSUED',
  BOOK_RETURNED: 'BOOK_RETURNED',
  FINE_CREATED: 'FINE_CREATED',
  FINE_PAID: 'FINE_PAID',
  FINE_WAIVED: 'FINE_WAIVED',
  RESERVATION_CREATED: 'RESERVATION_CREATED',
  RESERVATION_UPDATED: 'RESERVATION_UPDATED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  SETTINGS_CHANGED: 'SETTINGS_CHANGED',
};

module.exports = {
  ROLES,
  ISSUE_STATUS,
  FINE_STATUS,
  RESERVATION_STATUS,
  MEMBER_STATUS,
  MEMBER_TYPES,
  ACTIVITY_ACTIONS,
};
